name: listening-workflow
run-name: "Workflow completion processing"

on:
  workflow_run:
    workflows: ["workflow"]
    types:
      - completed

jobs:
  process-workflow-completion:
    runs-on: ubuntu-latest
    steps:
      - name: Write about results
        run: |
          echo ${{ github.event.workflow_run.conclusion == 'success' }}
      - name: Add check
        uses: LouisBrunner/checks-action@v1.6.1
        if: always()
        with:
          sha: ${{ github.event.workflow_run.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Test XYZ
          conclusion: ${{ github.event.workflow_run.conclusion }}
          output: |
            {"summary":"Some summary"}
      - name: Run the action
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Test run'
          description: 'Passed'
          state: 'success'
          target_url: ${{ github.event.workflow_run.html_url }}
          sha: ${{ github.event.workflow_run.head_sha }}
