name: listening-workflow
run-name: "Workflow completion processing"

on:
  workflow_run:
    workflows: [workflow-1]
    types:
      - completed

permissions:
  actions: write

jobs:
  process-workflow-completion:
    runs-on: ubuntu-latest
    steps:
      - name: Write about results
        run: |
          cat ${{ env.GITHUB_EVENT_PATH }}