name: listening-workflow
run-name: "Workflow run processing"

on:
  workflow_run:
    workflows: ["workflow-1"]

jobs:
  process-workflow-completion:
    runs-on: ubuntu-latest
    steps:
      - name: Map run status to commit state
        if: github.event.workflow_run.status != 'completed'
        run: |
          case ${{ github.event.workflow_run.status }} in
             requested|queued|in_progress|pending|waiting)
                result=pending;;
          esac
          echo "COMMIT_STATE=$result" >> $GITHUB_ENV
      - name: Map run conclusion to commit state
        if: github.event.workflow_run.status == 'completed'
        run: |
          case ${{ github.event.workflow_run.conclusion }} in
             success)
                result=success;;
             failure|neutral|cancelled|timed_out|action_required|stale|null|skipped)
                result=failure;;
             startup_failure)
                result=error;;
          esac
          echo "COMMIT_STATE=$result" >> $GITHUB_ENV

      - name: Set commit status
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: ${{ github.event.workflow_run.name }}
          description: ${{ github.event.workflow_run.display_title }}
          state: ${{ env.COMMIT_STATE }}
          target_url: ${{ github.event.workflow_run.html_url }}
          sha: ${{ github.event.workflow_run.head_sha }}
