name: trigger-workflow
run-name: "PR commands processing"

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

permissions:
  actions: write

jobs:
  dispatch-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: '@test'
      - name: Do something
        if: steps.check.outputs.triggered == 'true'
        run: |
          echo ${{ github.sha }}
