name: trigger-workflow
run-name: "PR commands processing"

on:
  issue_comment:
    types: [created]

permissions:
  actions: write

jobs:
  dispatch-test-workflow:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/test')
    runs-on: ubuntu-latest
    steps:
      - name: Add comment to PR
        id: get-pr-ref
        uses: actions/github-script@v6
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ github.event.issue.number }}
            });
            return pr.head.ref;
          result-encoding: string

      - name: Do something
        run: |
          echo "${{steps.get-pr-ref.outputs.result}}"
