name: using-flow

on:
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      arg:
        type: string
        description: a workflow input
        required: true
        default: default_value

permissions:
  id-token: write
  actions: write
  contents: read
  pull-requests: write
  checks: write

jobs:
  run-workflow:
#    if: contains(github.event.comment.body, '/test')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "test executed"
      - uses: LouisBrunner/checks-action@v1.6.1
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Test XYZ
          conclusion: ${{ job.status }}
          sha: ${{env.GITHUB_SHA}}
          output: |
            {"summary":"${{ steps.test.outputs.summary }}"}
