name: using-flow

on:
#  pull_request:
#    branches:
#      - main
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      arg:
        type: string
        description: a workflow input
        required: true
        default: default_value

permissions:
  id-token: write
  actions: write
  contents: read
  pull-requests: write
  checks: write
  statuses: write

jobs:
  run-workflow:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/test')
    runs-on: ubuntu-latest
    steps:
      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch

      - name: Set latest commit status as pending
        uses: myrotvorets/set-commit-status-action@master
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending

      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - name: "Execute test"
        run: |
          echo "test executed"

      - name: Set latest commit status as ${{ job.status }}
        uses: myrotvorets/set-commit-status-action@master
        if: always()
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}