name: using-flow

on:
  workflow_dispatch:
    inputs:
      username:
        type: string
        required: true

jobs:
  call-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      username: ${{ inputs.username }}
