name: using-flow

on:
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      arg:
        type: string
        description: a workflow input
        required: true
        default: default_value

permissions:
  id-token: write
  actions: write
  contents: read
  pull-requests: write
  checks: write

jobs:
  run-workflow:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "test executed"
      - run: >
          curl -L 
            -X POST 
            -H "Accept: application/vnd.github+json" 
            -H "Authorization: Bearer <YOUR-TOKEN>"
            -H "X-GitHub-Api-Version: 2022-11-28" 
            https://api.github.com/repos/${{vars.GITHUB_REPOSITORY_OWNER}}/${{vars.GITHUB_REPOSITORY}}/check-runs 
            -d '{"name":"mighty_readme","head_sha":"${{vars.GITHUB_HEAD_REF}}","status":"completed","output":{"title":"Mighty Readme report","summary":"","text":""}}'
