name: using-flow

on:
  workflow_dispatch:

jobs:
  call-workflow:
    strategy:
      matrix:
        include:
          - username: Anton
          - username: Vasya
          - username: Oleh
    uses: ./.github/workflows/reusable.yml
    with:
      username: ${{ matrix.username }}
