name: workflow-2

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      arg:
        type: string
        description: a workflow input
        required: true
        default: default_value

permissions:
  id-token: write
  actions: write
  contents: read
  pull-requests: write
  checks: write
  statuses: write

jobs:
  run-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: "Execute some task"
        run: |
          echo "test executed"