name: workflow-1

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main


jobs:
  run-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
      - name: Check checkout result
        run: |
          sleep 10
          cat file.txt