name: Workflow

on:
  workflow_dispatch:
  # push:
  #   branches: [main]

jobs:
  run-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: "Execute test"
        run: |
          echo "test executed"
          