name: PR triggered workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - development


jobs:
  run-tests:
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        include:
          # for main branch run all tests, otherwise PRSmoke
          - tags: ${{ github.base_ref != 'main' && 'PRSmoke' || '-dummy-negate-tag' }}
    uses: ./.github/workflows/workflow.yml
    with:
      tags: ${{ matrix.tags }}
