name: workflow-1

on:
  workflow_dispatch:
    inputs:
      arg:
        type: string
        description: a workflow input
        required: true
        default: default_value

permissions:
  id-token: write
  actions: write
  contents: read
  pull-requests: write
  checks: write
  statuses: write

jobs:
  run-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: "Execute test"
        run: |
          echo "test executed"