name: "Parameterized workflow"

on:
  workflow_call:
    inputs:
      tags:
        type: string
        required: false

permissions:
  id-token: write
  actions: write
  contents: read
  checks: write

jobs:
  build:
    name: ${{ inputs.name }}
    timeout-minutes: 120
    runs-on: self-hosted
    steps:
      - name: Set env values
        run: |
          echo TAGS ARE: ${{ inputs.tags }}          
