name: PR triggered workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - development


jobs:
  matrix_prep:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.set-tags.outputs.tags }}
    steps:
      - id: set-tags
        run: |
          # for main branch run all tests, otherwise PRSmoke
          case ${{ github.base_ref }} in
          main)
          tests_tags="main"
          ;;
          development)
          tests_tags="PRSmoke"
          ;;
          *)
          tests_tags="PRSmoke"
          ;;
          esac                
          echo "tags=$tests_tags" >> $GITHUB_OUTPUT
  run-tests:
    needs: matrix_prep
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        include:
          - tags: ${{ needs.matrix_prep.outputs.tags }}
    uses: ./.github/workflows/workflow.yml
    with:
      tags: ${{ matrix.tags }}
